id: P008207
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD105878
  title: ཨ་ཁྲིད་ཐུན་མཚམས་བཅོ་ལྔ་པ་མ་བུ་ཅ་ལག་དང་བཅས་པ།
  author: ''
  volumes:
    246fdec766514215abb3db003ba82931:
      image_group_id: I1PD105880
      title: ''
      volume_number: 1
      total_pages: 270
      base_file: v001.txt
